fixtures:
  repositories:
    hash_file:
      repo: git://github.com/fiddyspence/puppet-hash_file.git
      ref: 1.0.2
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.6.0
  symlinks:
    named_interfaces: "#{source_dir}"
